# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: PSD
author: Jordan Hutahaean
logo: jeriko.jpeg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book
  path_to_book: docs
  branch: master

# Add GitHub buttons to your book
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: false
  collapse_navigation: false
  favicon: jeriko.jpeg
  extra_footer: |
    <p style="text-align:center;">© 2025 Jordan Hutahaean</p>
